export const productsData = [
  {
    id: 1,
    title: "Gildan Men T-Shirt",
    quantity: 1,
    availableSizes: ["X", "L", "XL", "XXL"],
    price: 30,
  },
  {
    id: 2,
    title: "Hanes Cotton T-Shirt",
    quantity: 1,
    availableSizes: ["S", "X", "M", "L", "XL"],
    price: 25,
  },
  {
    id: 3,
    title: "Champion T-Shirt",
    quantity: 1,
    availableSizes: ["X", "XL"],
    price: 60,
  },
  {
    id: 4,
    title: "Unisex T-Shirt",
    quantity: 1,
    availableSizes: ["S", "L", "XXL"],
    price: 45,
  },
  {
    id: 5,
    title: "Russell T-Shirt",
    quantity: 1,
    availableSizes: ["X", "M", "XXL"],
    price: 40,
  },
  {
    id: 6,
    title: "Puma Men T-Shirt",
    quantity: 1,
    availableSizes: ["S", "L", "XL", "XXL"],
    price: 55,
  },
  {
    id: 7,
    title: "Gap T-Shirt",
    quantity: 1,
    availableSizes: ["X", "L", "XL"],
    price: 25,
  },
  {
    id: 8,
    title: "Ritual T-Shirt",
    quantity: 1,
    availableSizes: ["X", "M", "L", "XL", "XXL"],
    price: 40,
  },
  {
    id: 9,
    title: "Disney Men T-Shirt",
    quantity: 1,
    availableSizes: ["L", "XL", "XXL"],
    price: 45,
  },
  {
    id: 10,
    title: "Calvin T-Shirt",
    quantity: 1,
    availableSizes: ["S", "XL", "XXL"],
    price: 30,
  },
];
